# -*- coding: utf-8 -*-
"""Untitled1.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/19ALu4kRS2VjCD_XlkEKW0e3aPMec_eOK
"""

name="deepak"
age=22
CGPA=9.5
placed=True
print("student name:",name)
print(type(name))
print(type(age))
print(type(CGPA))
print(type(placed))

"""list"""

name=["deepak","gilli","shame"]
marks=[90,50,45]
print(marks[2])